spring.application.name=NaengTulCook

spring.datasource.url=jdbc:mysql://3.27.133.52:3306/trendithon
spring.datasource.username=root
spring.datasource.password=1111
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/swagger-ui/index.html
openai.model=gpt-3.5-turbo
openai.api.key=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
openai.api.url= https://api.openai.com/v1/chat/completions

spring.servlet.multipart.enabled=true
